### ISSUE TITLE
Inside a bash function, a bracket inside a string or a comment will give an error

### ISSUE THREAD

**Issue by idillon-sfl** [amaanq/tree-sitter-bitbake#13]
A bracket inside a string inside a function gives an error
```
d() {
  t = '{'
}
```

A bracket inside a comment gives an error
```
do() {
  # {
}
```

It does work inside python functions, though

Thank you

**Comment by amaanq** [comment]
I'll fix the string one tomorrow, comment one should be fixed and I pushed a bunch of fixes just now
