### ISSUE TITLE
Line continuation with backslashe generates error in some cases

### ISSUE THREAD

**Issue by idillon-sfl** [amaanq/tree-sitter-bitbake#14]
I noticed the line continuation with backslashes generates errors in some cases. Unfortunately, I failed to understand exactly when it happens. Most of the time, it seems not to be an issue.

Here two real life examples taken from Poky:
https://git.yoctoproject.org/poky/tree/meta/classes/recipe_sanity.bbclass#n45
https://git.yoctoproject.org/poky/tree/meta/classes/copyleft_filter.bbclass#n76

Here an other example I made myself:
``` python
def example():
    print('test', \
        True
    )
```

Curiously, in this example, the parsing works properly if `True` is replaced by a string.

Thank you

**Comment by amaanq** [comment]
Fixed, thanks
