### ISSUE TITLE
Functions defined into an other function gives an error

### ISSUE THREAD

**Issue by idillon-sfl** [amaanq/tree-sitter-bitbake#15]
A function defined into an other function gives an error

Here's a real-life example from meta-openembedded: https://github.com/openembedded/meta-openembedded/blob/4dbbef7a39ad18206ca6cebf7a1e08aebe5b5a65/meta-oe/recipes-support/opencv/opencv_4.8.0.bb#L46

Here's a minimal example:
```
func() {
    nestedfunc() {
        echo "test"
    }
}
```

output:
```
(recipe [0, 0] - [5, 0]
  (ERROR [0, 0] - [4, 1]
    (function_definition [0, 0] - [3, 5]
      (identifier [0, 0] - [0, 4])
      (ERROR [0, 7] - [1, 16]
        (ERROR [1, 4] - [1, 14]))
      (shell_content [2, 8] - [2, 19]))))
```

Thank you

**Comment by amaanq** [comment]
Fixed, thanks
