### ISSUE TITLE
Can we make the identifier optional for variable expansion syntax?

### ISSUE THREAD

**Issue by WilsonZiweiWang** [amaanq/tree-sitter-bitbake#7]
Version: 1.0.1
Currently, the `${}` with an identifier will be treated as variable expansion:
`variable_expansion: $ => seq('${', $.identifier, '}'),`
when there is an empty `${}`, the generated tree node is unrelated to variable expansion.
![image](https://github.com/amaanq/tree-sitter-bitbake/assets/47988425/e72b565f-9ea1-4004-a552-aa6e0c21325d)

Can we make the identifier optional such that `${}` alone can be treated as variable expansion?
The language extension will be able to provide the desired completion even with empty `${}`

**Comment by amaanq** [comment]
Is it valid bitbake as in it's to be treated as the text "${}" literally? Or is it completely invalid bitbake?

**Comment by WilsonZiweiWang** [comment]
> Is it valid bitbake as in it's to be treated as the text "${}" literally? Or is it completely invalid bitbake?

Bitbake produces `""`. No error was raised.

**Comment by amaanq** [comment]
Fixed on master, will make a new release
