### ISSUE TITLE
Can't handle override syntax in the last line of the file

### ISSUE THREAD

**Issue by WilsonZiweiWang** [amaanq/tree-sitter-bitbake#9]
Version: 
1.0.1

Current behaviour:
The same overrides syntax in tree-sitter is treated differently as shown in these screenshots. When it is not in the last line in the file, it is treated as the override (even though it is still picking up the content following). When it is in the last line, it is treated as an identifier and nothing related to override anymore. 
![image](https://github.com/amaanq/tree-sitter-bitbake/assets/47988425/7ed6ed8c-5fdb-4138-91d5-4c1a3670528a)
![image](https://github.com/amaanq/tree-sitter-bitbake/assets/47988425/25d1d266-f794-4783-b641-e1b160256873)

Expectation:
When it encounters `MYVAR:a:` in the last line of the file, it still treats it as `overrides` or partially. This is an override statement yet to be completed and it will benefit the completion in language extension.

Good to have:
When it encounters `MYVAR:a:` **not** in the last line of the file, the current one is enough to identify an override syntax to perform further actions. But it will be nice if it won't pick up the content following as part of the override syntax.

**Comment by WilsonZiweiWang** [comment]
I just realized that variable expansion in override is not handled:
`FILES:${PN}:append = "/usr/bin/example" `
![image](https://github.com/amaanq/tree-sitter-bitbake/assets/47988425/051e0809-ef15-43a0-9013-ec91b4a63739)

It would be nice to treat it as override statement's child even in a case like this:
`FILES:${PN}: = "/usr/bin/example"` where the second override is about to be typed after the `:`
![image](https://github.com/amaanq/tree-sitter-bitbake/assets/47988425/31911320-1e68-4c58-805f-d76abd5d2703)

**Comment by amaanq** [comment]
tree-sitter's error recovery can't be fine tuned for specific cases, it's a general error recovery mechanism so I'm not going to fix this - but the valid variable expansion code has been fixed
